# Generated by Django 3.2 on 2023-03-29 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('titles', '0003_auto_20230329_2338'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='title',
        ),
    ]
